### PR TITLE
5.1 Made separate modules in the project using IIFE.

### PR DESCRIPTION
**Pull request by olga-kravchenko**

### CODE REVIEW

**Comment by rmk1409** [comment]
1. Added main.js.
2. Rename date to data.
3. Add empty line before add scripts in .html.
4. Change names & move logic according by the technical specification.

**Comment by rmk1409** [comment]
1. Remove extra empty lines.
2. Move EMPTY_STRING & ONE_HUNDRED into proper module.
3. Rename 'uploadPhoto' to proper name by its logic.
4. Don't export uploadButton in form.js(remove 2 'change' listeners & add reset functions)
5. Don't export effectLevel in form.js(find it again)
6. Use querySelector in closer places.
7. Replace 'fori' to 'for of' or 'forEach'(better than 'for of').
8. in gallery change order of logic: preview.render & showModal()
9. refactor onEscKey
10. cancelButton???
11. simplify && refactor everything!!

**Comment by rmk1409** [comment]
1. "Use querySelector in closer places."
2. "Remove extra empty lines."
3. "Move EMPTY_STRING & ONE_HUNDRED into proper module."
4. forEach: 
`
    photosNew.forEach((photoNew)=>{
      const newPhoto = window.picture.render(photoNew);
      photos = photosNew;
      fragment.appendChild(newPhoto);
    });`
5. Rename "photosNew" & refactor 'render' & 'addListeners' in 'gallery'.

**Comment by rmk1409** [comment]
1. Refoctor 'createNewComment' & 'addCommentsToParent' in 'preview'. Also refactor 'render'.
2. Make an order in 'gallery' in 'activate', in 'form' in 'onUploadBottomChange'
3. Expand 'constants'.
4. Refactor 'getPhotos' & 'getRandomComment' in 'data'
5. Rename 'Bottom'.
6. Refactor 'checkWithRegex' in 'hashtag'
` isValidity = hashtags.every((hashtag) => regex.test(hashtag));
    currentErrorMessage = isValidity ? Message.NO_ERROR : Message.ERROR_IN_HASHTAG;`
Also refactor 'checkHashtag', add 'isEmpty'
7. Refactor 'addListeners' in 'zoom'.

**Comment by olga-kravchenko** [comment]
Fixed everything!

**Pull request merged**
